config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :posts

  controller :rodauth do
    get "download-recovery-codes"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  include Rodauth::Rails.model

  has_many :posts
  has_one :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/oauth_application.rb
# frozen_string_literal: true

class OauthApplication < ApplicationRecord
end

app/models/oauth_grant.rb
# frozen_string_literal: true

class OauthGrant < ApplicationRecord
end

app/models/oauth_token.rb
# frozen_string_literal: true

class OauthToken < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = current_account.posts.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_account.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_account.posts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/rodauth_controller.rb
class RodauthController < ApplicationController
  # used by Rodauth for rendering views, CSRF protection, and running any
  # registered action callbacks and rescue_from handlers

  def download_recovery_codes
    rodauth.require_authentication

    send_data rodauth.recovery_codes.join("\n"),
      filename: "myapp-recovery-codes.txt",
      type: "text/plain"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/_flash.html.erb
<% if notice %>
  <div class="alert alert-success">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger">
    <%= alert %>
  </div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light border-bottom mb-4">
  <% if rodauth.logged_in? %>
    <div class="container">
      <%= link_to "Rails App" , root_path, class: "navbar-brand" %>
      <div class="navbar-collapse">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Posts" , posts_path, class: "nav-link #{" active" if request.path.start_with?("/posts")}" %>
          </li>
          <li class="nav-item">
            <%= link_to "Client Applications" , rodauth.oauth_applications_path, class: "nav-link #{" active" if request.path.start_with?("/oauth-applications")}" %>
          </li>
        </ul>
      </div>
    </div>

    <div class="dropdown">
      <button class="btn btn-info dropdown-toggle" data-bs-toggle="dropdown" type="button">
        <%= current_account.profile.name %>
      </button>
      <div class="dropdown-menu dropdown-menu-end">
        <%= link_to "Change password" , rodauth.change_password_path, class: "dropdown-item" %>
        <%= link_to "Change email" , rodauth.change_login_path, class: "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Manage MFA" , rodauth.two_factor_manage_path, class: "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Close account" , rodauth.close_account_path, class: "dropdown-item text-danger" %>
        <%= link_to "Sign out" , rodauth.logout_path, data: { turbo_method: :post }, class: "dropdown-item" %>
      </div>
    </div>
  <% else %>
    <div>
      <%= link_to "Sign in" , rodauth.login_path, class: "btn btn-outline-primary" %>
      <%= link_to "Sign up" , rodauth.create_account_path, class: "btn btn-success" %>
    </div>
  <% end %>
</nav>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RodauthBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "navbar" %>
    <div class="container">
      <%= render "flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/rodauth/_login_form.html.erb
<%= form_with url: rodauth.login_path, method: :post, data: { turbo: false } do |form| %>
  <% if rodauth.skip_login_field_on_login? %>
    <div class="form-group mb-3">
      <%= form.label "login", rodauth.login_label, class: "form-label" %>
      <%= form.email_field rodauth.login_param, value: params[rodauth.login_param], id: "login", readonly: true, class: "form-control-plaintext" %>
    </div>
  <% else %>
    <div class="form-group mb-3">
      <%= form.label "login", rodauth.login_label, class: "form-label" %>
      <%= form.email_field rodauth.login_param, value: params[rodauth.login_param], id: "login", autocomplete: "email", required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.login_param)}", aria: ({ invalid: true, describedby: "login_error_message" } if rodauth.field_error(rodauth.login_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.login_param), class: "invalid-feedback", id: "login_error_message") if rodauth.field_error(rodauth.login_param) %>
    </div>
  <% end %>

  <% unless rodauth.skip_password_field_on_login? %>
    <div class="form-group mb-3">
      <%= form.label "password", rodauth.password_label, class: "form-label" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_param)}", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "invalid-feedback", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.submit rodauth.login_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/add_recovery_codes.html.erb
<% content_for :title, rodauth.add_recovery_codes_page_title %>

<% if rodauth.recovery_codes.any? %>
  <p class="my-3">
    Copy these recovery codes to a safe location.
    You can also download them <%= link_to "here" , download_recovery_codes_path %>.
  </p>

  <div class="d-inline-block mb-3 border border-info rounded px-3 py-2">
    <% rodauth.recovery_codes.each_slice(2) do |code1, code2| %>
      <div class="row text-info text-left">
        <div class="col-lg my-1 font-monospace">
          <%= code1 %>
        </div>
        <div class="col-lg my-1 font-monospace">
          <%= code2 %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<pre id="recovery-codes"><%= rodauth.recovery_codes.map { |s| h(s) }.join("\n\n") %></pre>

<% if rodauth.can_add_recovery_codes? %>
  <%== rodauth.add_recovery_codes_heading %>
  <%= render template: "rodauth/recovery_codes", layout: false %>
<% end %>

app/views/rodauth/authorize.html.erb
<%= form_tag rodauth.authorize_path, method: :post do %>
  <p class="lead">The application <%= rodauth.oauth_application[rodauth.oauth_applications_name_column] %> would like to access your data.</p>

  <div class="form-group">
    <h1 class="display-6"><%= rodauth.scopes_label %></h1>

    <% rodauth.scopes.each do |scope| %>
      <% is_default = scope == rodauth.oauth_application_default_scope %>
      <div class="form-check">
        <%= check_box_tag "scope[]", scope, is_default, disabled: is_default, id: scope, class: "form-check-input" %>
        <%= label_tag scope, scope, class: "form-check-label" %>
        <%= hidden_field_tag "scope[]", scope if is_default %>
      </div>
    <% end %>
    <%= hidden_field_tag :client_id, params[:client_id] %>
    <% %i[access_type response_type state nonce redirect_uri code_challenge code_challenge_method].each do |oauth_param| %>
      <% if params[oauth_param] %>
        <%= hidden_field_tag oauth_param,  params[oauth_param] %>
      <% end %>
    <% end %>
    <% if params[:response_mode] %>
      <%= hidden_field_tag :response_mode, params[:response_mode] %>
    <% end %>
  </div>
 <p class="text-center">
    <%= submit_tag "Authorize", class: "btn btn-outline-primary" %>
    <%= link_to "Cancel", "#{rodauth.redirect_uri}?error=access_denied&error_description=The+resource+owner+or+authorization+server+denied+the+request#{"&state=\#{rodauth.state}" if params[:state] }", class: "btn btn-outline-danger" %>
  </p>
<% end %>

app/views/rodauth/close_account.html.erb
<% content_for :title, rodauth.close_account_page_title %>

<%= form_with url: rodauth.close_account_path, method: :post, data: { turbo: false } do |form| %>
  <% if rodauth.close_account_requires_password? %>
    <div class="form-group mb-3">
      <%= form.label "password", rodauth.password_label, class: "form-label" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_param)}", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "invalid-feedback", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.submit rodauth.close_account_button, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/rodauth/logout.html.erb
<% content_for :title, rodauth.logout_page_title %>

<%= form_with url: rodauth.logout_path, method: :post, data: { turbo: false } do |form| %>
  <% if rodauth.features.include?(:active_sessions) %>
    <div class="form-group mb-3">
      <div class="form-check">
        <%= form.check_box rodauth.global_logout_param, id: "global-logout", class: "form-check-input" %>
        <%= form.label "global-logout", rodauth.global_logout_label, class: "form-check-label" %>
      </div>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.submit rodauth.logout_button, class: "btn btn-warning" %>
  </div>
<% end %>

app/views/rodauth/multi_phase_login.html.erb
<% content_for :title, rodauth.multi_phase_login_page_title %>

<%= render "login_form_header" %>
<%== rodauth.render_multi_phase_login_forms %>
<%= render "login_form_footer" %>

app/views/rodauth/new_oauth_application.html.erb
<%= form_tag rodauth.oauth_applications_path, method: :post, class: "form-horizontal" do %>
  <h2>Register Oauth Application</h2>
  <%= rodauth.field_error('scope') %>
  <div class="form-group">
    <%= label_tag "name", "Name" %>
    <%= text_field_tag "name", rodauth.param('name'), class: "form-control#{' is-invalid' if rodauth.field_error('name')}" %>
    <%= rodauth.field_error('name') %>
  </div>
  <div class="form-group">
    <%= label_tag "description", "Description" %>
    <%= text_field_tag "description", rodauth.param('description'), class: "form-control#{' is-invalid' if rodauth.field_error('description')}" %>
    <%= rodauth.field_error('description') %>
  </div>
  <div class="form-group">
    <%= label_tag "homepage_url", "Homepage URL" %>
    <%= text_field_tag "homepage_url", rodauth.param('homepage_url'), class: "form-control#{' is-invalid' if rodauth.field_error('homepage_url')}" %>
    <%= rodauth.field_error('homepage_url') %>
  </div>
  <div class="form-group">
    <%= label_tag "redirect_uri", "Redirect URL" %>
    <%= text_field_tag "redirect_uri", rodauth.param('redirect_uri'), class: "form-control#{' is-invalid' if rodauth.field_error('redirect_uri')}" %>
    <%= rodauth.field_error('redirect_uri') %>
  </div>
  <div class="form-group">
    <%= label_tag "client_secret", "Secret (make it random and at least 32 character-long)" %>
    <%= text_field_tag "client_secret", rodauth.param('client_secret'), class: "form-control#{' is-invalid' if rodauth.field_error('client_secret')}" %>
    <%= rodauth.field_error('client_secret') %>
  </div>
  <% rodauth.oauth_application_scopes.each do |scope| %>
    <div class="form-check">
      <%= check_box_tag "scopes[]", scope, scope == rodauth.oauth_application_default_scope, id: scope, class: "form-check-input" %>
      <%= scope %>
    </div>
  <% end %>
  <div class="form-group">
    <%= submit_tag "Register", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/oauth_applications.html.erb
<% oauth_applications_ds = rodauth.scope.instance_variable_get(:@oauth_applications) %>
<% apps_count = oauth_applications_ds.count %>
<div class="btn-group" role="group" aria-label="Buttons">
  <%= link_to "New Oauth Application",  "#{rodauth.oauth_applications_path}/new", class: "btn btn-secondary" %>
</div>
<% if apps_count.zero? %>
  <p>No oauth applications yet!</p>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Client ID (<%= apps_count %>)</th>
        <th scope="col">Name</th>
        <th scope="col">Homepage</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% oauth_applications_ds.each do |application| %>
        <tr>
          <td><%= application[rodauth.oauth_applications_client_id_column] %></td>
          <td><%= application[rodauth.oauth_applications_name_column] %></td>
          <td><%= application[rodauth.oauth_applications_homepage_url_column] %></td>
          <td><%= link_to "Show",  rodauth.oauth_application_path(application[rodauth.oauth_applications_id_column]) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/rodauth/recovery_auth.html.erb
<% content_for :title, rodauth.recovery_auth_page_title %>

<%= form_with url: rodauth.recovery_auth_path, method: :post, data: { turbo: false } do |form| %>
  <div class="form-group mb-3">
    <%= form.label "recovery-code", rodauth.recovery_codes_label, class: "form-label" %>
    <%= form.text_field rodauth.recovery_codes_param, value: "", id: "recovery-code", autocomplete: "off", required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.recovery_codes_param)}", aria: ({ invalid: true, describedby: "recovery-code_error_message" } if rodauth.field_error(rodauth.recovery_codes_param)) %>
    <%= content_tag(:span, rodauth.field_error(rodauth.recovery_codes_param), class: "invalid-feedback", id: "recovery-code_error_message") if rodauth.field_error(rodauth.recovery_codes_param) %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit rodauth.recovery_auth_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/recovery_codes.html.erb
<% content_for :title, rodauth.recovery_codes_page_title %>

<%= form_with url: rodauth.recovery_codes_path, method: :post, data: { turbo: false } do |form| %>
  <% if rodauth.two_factor_modifications_require_password? %>
    <div class="form-group mb-3">
      <%= form.label "password", rodauth.password_label, class: "form-label" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_param)}", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "invalid-feedback", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.submit rodauth.recovery_codes_button || rodauth.view_recovery_codes_button, name: (rodauth.add_recovery_codes_param if rodauth.recovery_codes_button), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/remember.html.erb
<% content_for :title, rodauth.remember_page_title %>

<%= form_with url: rodauth.remember_path, method: :post, data: { turbo: false } do |form| %>
  <fieldset class="form-group mb-3">
    <div class="form-check">
      <%= form.radio_button rodauth.remember_param, rodauth.remember_remember_param_value, id: "remember-remember", class: "form-check-input" %>
      <%= form.label "remember-remember", rodauth.remember_remember_label, class: "form-check-label" %>
    </div>

    <div class="form-check">
      <%= form.radio_button rodauth.remember_param, rodauth.remember_forget_param_value, id: "remember-forget", class: "form-check-input" %>
      <%= form.label "remember-forget", rodauth.remember_forget_label, class: "form-check-label" %>
    </div>

    <div class="form-check">
      <%= form.radio_button rodauth.remember_param, rodauth.remember_disable_param_value, id: "remember-disable", class: "form-check-input" %>
      <%= form.label "remember-disable", rodauth.remember_disable_label, class: "form-check-label" %>
    </div>
  </fieldset>

  <div class="form-group mb-3">
    <%= form.submit rodauth.remember_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/reset_password_request.html.erb
<% content_for :title, rodauth.reset_password_request_page_title %>

<%= form_with url: rodauth.reset_password_request_path, method: :post, data: { turbo: false } do |form| %>
  <%== rodauth.reset_password_explanatory_text %>

  <% if params[rodauth.login_param] && !rodauth.field_error(rodauth.login_param) %>
    <%= form.hidden_field rodauth.login_param, value: params[rodauth.login_param] %>
  <% else %>
    <div class="form-group mb-3">
      <%= form.label "login", rodauth.login_label, class: "form-label" %>
      <%= form.email_field rodauth.login_param, value: params[rodauth.login_param], id: "login", autocomplete: "email", required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.login_param)}", aria: ({ invalid: true, describedby: "login_error_message" } if rodauth.field_error(rodauth.login_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.login_param), class: "invalid-feedback", id: "login_error_message") if rodauth.field_error(rodauth.login_param) %>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.submit rodauth.reset_password_request_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/two_factor_auth.html.erb
<% content_for :title, rodauth.two_factor_auth_page_title %>

<ul>
  <% rodauth.two_factor_auth_links.sort.each do |_, link, text| %>
    <li><%= link_to text, link %></li>
  <% end %>
</ul>

app/views/rodauth/two_factor_manage.html.erb
<% content_for :title, rodauth.two_factor_manage_page_title %>

<% if rodauth.two_factor_setup_links.any? %>
  <%== rodauth.two_factor_setup_heading %>

  <ul>
    <% rodauth.two_factor_setup_links.sort.each do |_, link, text| %>
      <li><%= link_to text, link %></li>
    <% end %>
  </ul>
<% end %>

<% if rodauth.two_factor_remove_links.any? %>
  <%== rodauth.two_factor_remove_heading %>

  <ul>
    <% rodauth.two_factor_remove_links.sort.each do |_, link, text| %>
      <li><%= link_to text, link %></li>
    <% end %>
    <% if rodauth.two_factor_remove_links.length > 1 %>
      <li><%= link_to rodauth.two_factor_disable_link_text, rodauth.two_factor_disable_path %></li>
    <% end %>
  </ul>
<% end %>